// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1U25Zocfqt7EjfF3Ik6jwQ1mOqGZ03iM',
    appId: '1:1009629449532:web:7845ac4d09dc4ef7e92239',
    messagingSenderId: '1009629449532',
    projectId: 'mslogin-2feed',
    authDomain: 'mslogin-2feed.firebaseapp.com',
    storageBucket: 'mslogin-2feed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTT_GgqaD9pHuEgxhDvFk-smqY2P9fKVY',
    appId: '1:1009629449532:android:56319b3cbf153792e92239',
    messagingSenderId: '1009629449532',
    projectId: 'mslogin-2feed',
    storageBucket: 'mslogin-2feed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzC5mpxk6oBxuaZ0Aw_Vh2FTgcmQ0U_M',
    appId: '1:1009629449532:ios:5d4c4cc136b5df9ee92239',
    messagingSenderId: '1009629449532',
    projectId: 'mslogin-2feed',
    storageBucket: 'mslogin-2feed.firebasestorage.app',
    iosBundleId: 'com.example.fblogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQzC5mpxk6oBxuaZ0Aw_Vh2FTgcmQ0U_M',
    appId: '1:1009629449532:ios:5d4c4cc136b5df9ee92239',
    messagingSenderId: '1009629449532',
    projectId: 'mslogin-2feed',
    storageBucket: 'mslogin-2feed.firebasestorage.app',
    iosBundleId: 'com.example.fblogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1U25Zocfqt7EjfF3Ik6jwQ1mOqGZ03iM',
    appId: '1:1009629449532:web:8564414597f0187fe92239',
    messagingSenderId: '1009629449532',
    projectId: 'mslogin-2feed',
    authDomain: 'mslogin-2feed.firebaseapp.com',
    storageBucket: 'mslogin-2feed.firebasestorage.app',
  );
}
